artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/karoldvl/ESC-50/archive/master.zip
  local_data_file: artifacts/data_ingestion/ESC-50-master.zip
  unzip_dir: artifacts/data_ingestion
